name: Selenium Tests CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Maven
      run: mvn -version

    - name: Run Selenium Tests
      id: run-tests
      run: |
        mvn test | tee test_output.log

    - name: Store Logs as an Output
      id: capture-logs
      run: echo "logs=$(cat test_output.log | base64 -w 0)" >> $GITHUB_ENV  

    - name: Send Email on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Selenium Test Failure"
        body: "Check logs for details."
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: "GitHub Actions"

    - name: Send Email on Success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Selenium Test Execution Success"
        body: |
          The Selenium tests executed successfully.
      
          Test Results: ${{ job.status }}

          Execution Logs:
          $(echo "${{ env.logs }}" | base64 --decode)

          Check full details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: "${{ secrets.TRAINER_EMAIL }},${{ secrets.MENTOR_EMAIL }},${{ secrets.RECIPIENT_EMAIL }}"
          from: "GitHub Actions"
          


